# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-14 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('place_id', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('links_gm', models.TextField()),
                ('phone', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('text', models.TextField()),
                ('w_to', models.TimeField()),
                ('day', models.PositiveSmallIntegerField()),
                ('expire_date', models.CharField(blank=True, max_length=50)),
                ('priority', models.PositiveSmallIntegerField()),
                ('text_id', models.PositiveIntegerField()),
                ('w_from', models.TimeField()),
                ('price', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
